config/routes.rb
Birdcage::Application.routes.draw do

  root :to => "home#index"
  match "home/index" => "home#index" #needed to serve javascript

  match "/auth/twitter/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout

  resources :tweets do
    member do
      put :increase_priority, :as => :increase_priority
      put :set_top_priority, :as => :set_top_priority
    end
    collection do
      put :randomize, :as => :randomize
    end
  end

  match "users/activate" => "users#activate", :via => :put
  resources :users

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  
  MIN_PRIORITY_INCREMENT = 0.00000001

  def increase_priority

    tweets_above = Tweet.where("user_id = ? and sent = ? and priority > ?", user_id, false, priority).order("priority").limit(2).all
    if (tweets_above.length == 2)
      increment = (tweets_above[1].priority - tweets_above[0].priority) / 2
      increment = increment == 0 ? MIN_PRIORITY_INCREMENT : increment
      self[:priority] = tweets_above[0].priority + increment
    elsif (tweets_above.length == 1)
      self[:priority]=tweets_above[0].priority + MIN_PRIORITY_INCREMENT
    else
      self[:priority] += MIN_PRIORITY_INCREMENT
    end

    save!

  end
  
  def set_top_priority
    max_prio = Tweet.where("user_id=?", user_id).maximum("priority")
    self[:priority] = max_prio + MIN_PRIORITY_INCREMENT
    
    save!
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  def self.create_with_omniauth(auth)
    create! do |user|
      user.name = auth["info"]["name"]
      user.uid = auth["uid"]
      user.provider = auth["provider"]
      user.token = auth["credentials"]["token"]
      user.secret = auth["credentials"]["secret"]
    end
  end

  def latest_tweet_time
    if last_post 
      last_post.to_s(:short) 
    else
      ""
    end
  end

  def next_tweet_time
    if last_post && last_post + post_interval.minutes - Time.now > 0
     last_post + post_interval.minutes
    else
      Time.now
    end
  end

  def unsent_tweets
    tweets.where("sent = ?", false).order("priority desc, created_at asc")
  end

  def latest_tweet_content
    t = tweets.where("sent = ?", true).order("updated_at desc").first
    if t
      t.content
    else
      ""
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate, :set_user_time_zone
  helper_method :current_user
  
  private

      def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      end

      def authenticate
        unless current_user && (["test_jb", "test_jb2", "jbandi"].include?(current_user.name))
          msg = "Must be logged in!"
          if current_user
            msg = "Only restricted users are allowed access!"
          end
          redirect_to root_path, :notice => msg

        end
      end

      def set_user_time_zone
        Time.zone = current_user.time_zone if current_user
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate

  def index
    respond_to do |format|
      format.html do
        if (current_user)
          @tweet = Tweet.new
          @tweets = current_user.unsent_tweets unless !current_user
          @latest_tweet_content = current_user.latest_tweet_content unless !current_user
        end
      end
      format.js do
        @bitly_login = current_user.bitly_login
        @bitly_api_key = current_user.bitly_password
      end
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate

  def create

#    raise request.env["omniauth.auth"].to_yaml

    auth = request.env["omniauth.auth"]
    logger.info auth["info"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id

    redirect_to root_url, :notice => "Signed in!"

  end

  def failure
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.xml
  def index
    @tweets = Tweet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.xml
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.xml
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.xml
  def create
    @tweet = Tweet.new(params[:tweet])

    puts "Current user: " + current_user.name
    
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to(:back, :notice => 'Tweet was successfully created.') }
        format.xml  { render :xml => @tweet, :status => :created, :location => @tweet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tweets/1
  # PUT /tweets/1.xml
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to(@tweet, :notice => 'Tweet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.xml
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to(tweets_url) }
      format.xml  { head :ok }
    end
  end

  def increase_priority
    puts "increase"

    @tweet = Tweet.find(params[:id])
    @tweet.increase_priority

    redirect_to(:back, :notice => 'Tweet was upped!')
  end
  
  def set_top_priority
    puts "increase"

    @tweet = Tweet.find(params[:id])
    @tweet.set_top_priority

    redirect_to(:back, :notice => 'Tweet was put to top!')
  end

  def randomize
    puts "randomize"

    for t in current_user.unsent_tweets do
      t.priority = rand
      t.save!
    end

    redirect_to(:back, :notice => 'Tweets randomized!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def activate
    puts "hello activate2 /" + params.to_yaml + "/"

    current_user.active=params[:user][:active]
    current_user.save

    redirect_to(:back )
    
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(:bitly_login => params[:user][:bitly_login], 
                                  :bitly_password => params[:user][:bitly_password],
                                  :post_interval => params[:user][:post_interval],
                                  :time_zone => params[:user][:time_zone])
        format.html { redirect_to(root_url, :notice => 'User was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% content_for :head do %>
  <script src="/home/index.js" type="text/javascript"></script>
<% end %>


<h1>Birdcage - Let your tweets escape one at a time...</h1>
<p id="notice"><%= notice %></p>

<% if !current_user %>
    <%= link_to "Sign in with Twitter", "auth/twitter" %>
<% else %>
    Welcome <%= current_user.name %>!
    <%= link_to "Sign out!", signout_path %>
    <%= link_to "Edit user data", edit_user_path(current_user) %>
    <br/>
    <br/>
    <%= form_for(current_user, :url => "users/activate", :html=> {:id=>"form_user_activate"}) do |f| %>
        Active: <%= f.check_box :active, :id=>"user_active" %>
        Last post: <%= current_user.latest_tweet_time %>
        - Next post in <%= time_ago_in_words current_user.next_tweet_time %>
        <br/>
        Latest tweet: <%= @latest_tweet_content %>
    <% end %>
    <br/>
    <%= form_for(@tweet) do |f| %>

        <div id="create_tweet">
          <%= f.label "New Tweet" %>
          <span id="tweet_remaining_count">140</span>
          <br/>
          <%= f.text_area :content, :rows => 7 %>
        </div>
        <%= f.submit %>
        <input type="button" id="shorten_url" value="Shorten URLs"/>
    <% end %>
    
    <br/>
    <h3>Your next tweets:</h3>
    
    <% @tweets.each do |tweet| %>
        <%= link_to "Up" , increase_priority_tweet_path(tweet), :method => :put %>
        <%= link_to "Top" , set_top_priority_tweet_path(tweet), :method => :put %>
        <%= link_to "Edit" , edit_tweet_path(tweet) %>
        <%= tweet.content %>
        <br/>
    <% end %>
    <%= link_to "Randomize" , randomize_tweets_path, :method => :put %>
<% end %>

app/views/home/index.js.erb
// Place your application-specific JavaScript functions and classes here
// This file is automatically included by javascript_include_tag :defaults

function parseUrl(text) {
        var bitly_url_regexp = /http:\/\/bit.ly\/[^\s]+/;
        var url_match = text.match(/(http:\/\/|https:\/\/|www\.)[^\s]+/g);

        for (var i in url_match) {
            var url = url_match[i];
            if (!url.match(bitly_url_regexp))
                return url;
        }
        return null;
}

function replaceUrl(text, url, short_url) {
    shortened_text = text.replace(url, short_url);
    $("#tweet_content").val(shortened_text);
    updateCount();
}

function shorten(text) {
    var url = parseUrl(text);

    if (url) {
        $.ajax({
            url: "http://api.bitly.com/v3/shorten?login=" + "<%= @bitly_login %>" + "&apiKey=" + "<%= @bitly_api_key %>" + "&longUrl=" + url,
            dataType: "jsonp",
            success: function(result) {
                var short_url = result["data"]["url"];
                replaceUrl(text, url, short_url)
            }
        })
    }
}

function updateCount() {
    $("#tweet_remaining_count").text(140 - $("#tweet_content").val().length);
}


$(document).ready(function() {
    $("#tweet_content").keyup(function() {
        updateCount();
    });
    $("#shorten_url").click(function() {
        shorten($("#tweet_content").val());
    });
    $("#form_user_activate").ajaxForm();
    $("#user_active").click(function(){
        $("#form_user_activate").trigger("submit");
    })

});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Birdcage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :sent %><br />
    <%= f.check_box :sent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Listing tweets</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Sent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.content %></td>
    <td><%= tweet.sent %></td>
    <td><%= link_to 'Show', tweet %></td>
    <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
    <td><%= link_to 'Destroy', tweet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>
<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @tweet.content %>
</p>

<p>
  <b>Sent:</b>
  <%= @tweet.sent %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_interval %><br />
    <%= f.number_field :post_interval %>
  </div>
  <div class="field">
    <%= f.label :bitly_login %><br />
    <%= f.text_field :bitly_login %>
  </div>
  <div class="field">
    <%= f.label :bitly_password %><br />
    <%= f.text_field :bitly_password %>
  </div>
  <div class="field">
    <%= f.label :time_zone %><br />
    <%= f.time_zone_select :time_zone %><br />
  </div>    
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Home', root_url %>